break_into_partial_movies: false
camera_qualities:
  default_quality: high
  high:
    frame_rate: 60
    resolution: 1920x1080
  low:
    frame_rate: 15
    resolution: 854x480
  medium:
    frame_rate: 30
    resolution: 1280x720
  ultra_high:
    frame_rate: 60
    resolution: 3840x2160
directories:
  mirror_module_path: false
  output: /Users/ytj/manim
  raster_images: /Users/ytj/manim/images/rasters
  sounds: /Users/ytj/manim/sounds
  temporary_storage: /Users/ytj/manim/temporary files
  vector_images: /Users/ytj/manim/images/vector
style:
  background_color: '#000000'
  font: Consolas
tex:
  executable: latex
  intermediate_filetype: dvi
  template_file: tex_template.tex
  text_to_replace: '[tex_expression]'
universal_import_line: from manimlib import *
window_position: UR
